## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

# Documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/rdf-patch"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-base"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-cmds"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-dist"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-examples"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-fuseki"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-fuseki-server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-integration-tests"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-server-extra"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-server-http"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
  - package-ecosystem: "gradle"
    directory: "/rdf-delta-server-local"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - mjulianotq
