language: java
sudo: false
script: mvn verify
jdk:
  - oraclejdk8
##  - openjdk8
env:
##   global:
##     - JAVA_OPTS="-Xmx1024M -Xms512M"
notifications:
  email:
    # [always|never|change]
    on_success: change
    on_failure: always
