/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.seaborne.rdf-delta.java-conventions")
}

dependencies {
    implementation(project(":rdf-patch"))
    implementation(project(":rdf-delta-base"))
    implementation(project(":rdf-delta-client"))    
    implementation("org.apache.jena:jena-fuseki-main:4.0.0")
}

description = "RDF Delta :: Apache Jena Fuseki Integration"
